name: gltf
version: 2.0.0-dev.2.7
description: Library for loading and validating VRM assets
author: Isamsu Mogi
homepage: https://github.com/saturday06/VRM-Validator

dependencies:
  args: '^1.5.0'
  isolate: '^2.0.2'
  meta: '^1.1.6'
  path: '^1.6.2'
  vector_math: '^2.0.8'
  yaml: '^2.1.15'

dev_dependencies:
  build_runner: '^1.1.2'
  build_web_compilers: '^1.0.0'
  build_node_compilers: '^0.2.0'
  grinder: '^0.8.3'
  js: '^0.6.1+1'
  node_preamble: '^1.4.4'
  test: '^1.5.1'

environment:
  sdk: '>=2.1.0 <3.0.0'

executables:
  vrm_validator:
